name: Automatic Forecasting

on:
  schedule:
    # Run every 20 minutes to catch new questions quickly
    - cron: '*/20 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run forecasting bot
      env:
        GITHUB_ACTIONS: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LITELLM_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        LITELLM_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
        ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
        CHUTES_API_TOKEN: ${{ secrets.CHUTES_API_TOKEN }}
        NOTIFICATION_SENDER_EMAIL: ${{ secrets.NOTIFICATION_SENDER_EMAIL }}
        NOTIFICATION_SENDER_PASSWORD: ${{ secrets.NOTIFICATION_SENDER_PASSWORD }}
        NOTIFICATION_RECIPIENT_EMAIL: ${{ secrets.NOTIFICATION_RECIPIENT_EMAIL }}
        NOTIFICATION_SMTP_SERVER: ${{ secrets.NOTIFICATION_SMTP_SERVER || 'smtp.gmail.com' }}
        NOTIFICATION_SMTP_PORT: ${{ secrets.NOTIFICATION_SMTP_PORT || '587' }}
      run: |
        python main.py --mode tournament

    - name: Upload forecast outputs
      uses: actions/upload-artifact@v4
      with:
        name: forecast-output-${{ github.run_number }}
        path: forecastoutput_*.md
        retention-days: 30