name: Complete POTUS End-to-End Forecasting

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *" # runs every 4 hours

jobs:
  complete_potus_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          echo "=== Installing complete forecasting system ==="
          pip install forecasting-tools python-dotenv asyncio

      - name: Run Complete POTUS Forecasting
        run: |
          echo "=== Starting Complete POTUS Forecasting at $(date) ==="
          echo "=== This will run the full multiforecaster process ==="

          python3 << 'EOF'
          import os
          import asyncio
          from datetime import datetime

          os.environ['GITHUB_ACTIONS'] = 'true'

          async def complete_potus_forecast():
              """Complete POTUS forecasting with full multiforecaster process."""
              print("🎯 COMPLETE POTUS END-TO-END FORECASTING")
              print("=" * 60)

              # Check environment
              api_key = os.getenv('OPENROUTER_API_KEY')
              metaculus_token = os.getenv('METACULUS_TOKEN')

              if not api_key:
                  print("❌ OPENROUTER_API_KEY not configured")
                  return False

              if not metaculus_token:
                  print("❌ METACULUS_TOKEN not configured")
                  return False

              print("✅ API keys configured")

              try:
                  # Import required modules
                  from forecasting_tools import MetaculusApi, ApiFilter, BinaryQuestion
                  from fallback_llm import create_research_fallback_llm, create_forecasting_fallback_llm, create_synthesis_fallback_llm

                  print("✅ Modules imported successfully")

                  # Step 1: Find POTUS questions
                  print("\\n📊 STEP 1: FINDING POTUS TOURNAMENT QUESTIONS")

                  all_questions = await MetaculusApi.get_questions_matching_filter(
                      ApiFilter(allowed_statuses=["open"], number_of_questions=50)
                  )

                  potus_questions = []
                  for q in all_questions:
                      if any(keyword in str(q.page_url).lower() for keyword in ['potus', 'bondi', 'attorney', 'trump', 'president']):
                          potus_questions.append(q)

                  if not potus_questions:
                      print("❌ No POTUS questions found")
                      return False

                  question = potus_questions[0]
                  print(f"✅ Found POTUS question: {question.question_text[:80]}...")
                  print(f"   URL: {question.page_url}")
                  print(f"   Type: {type(question).__name__}")

                  # Step 2: Create LLM instances
                  print("\\n🤖 STEP 2: INITIALIZING MULTIFORECASTER")

                  researcher_llm = create_research_fallback_llm(api_key=api_key, temperature=0.3, timeout=60, allowed_tries=2)
                  forecaster_llm = create_forecasting_fallback_llm(api_key=api_key, temperature=0.5, timeout=60, allowed_tries=2)
                  synthesizer_llm = create_synthesis_fallback_llm(api_key=api_key, temperature=0.3, timeout=60, allowed_tries=2)

                  print(f"✅ Researcher: {len(researcher_llm.model_chain)} models")
                  print(f"✅ Forecaster: {len(forecaster_llm.model_chain)} models")
                  print(f"✅ Synthesizer: {len(synthesizer_llm.model_chain)} models")

                  # Step 3: Research Phase
                  print("\\n📚 STEP 3: RESEARCH PHASE")

                  research_prompt = f"""Research this question thoroughly: {question.question_text}

          Page URL: {question.page_url}

          Task:
          1. Research the specific topic and context
          2. Look for relevant data, trends, and expert opinions
          3. Consider factors that could influence the outcome
          4. Examine similar questions or historical precedents

          Provide a comprehensive research summary covering all relevant aspects.
          Your response should be detailed and evidence-based.
          """

                  try:
                      print("🔄 Running research...")
                      research_response = await researcher_llm.invoke(research_prompt)
                      print(f"✅ Research completed ({len(research_response)} chars)")
                  except Exception as e:
                      print(f"❌ Research failed: {e}")
                      research_response = f"Research failed: {e}"

                  # Step 4: Individual Forecasts
                  print("\\n🔮 STEP 4: INDIVIDUAL FORECASTS")

                  forecast_prompt = f"""Based on the research, provide your forecast for this question:

          Question: {question.question_text}

          Research Summary:
          {research_response[:1500] if len(research_response) > 1500 else research_response}

          Task:
          Provide your forecast with:
          1. Probability assessment (0-100%)
          2. Reasoning (2-3 sentences)
          3. Format: "Probability: XX% - [Yes/No]"

          Consider the research evidence carefully.
          """

                  individual_forecasts = []

                  for i in range(2):  # 2 forecasters for time efficiency
                      print(f"   🤖 Forecaster {i+1}/2...")
                      try:
                          forecaster_prompt = f"{forecast_prompt}\\n\\nAs Forecaster {i+1}, provide your independent assessment:"
                          response = await forecaster_llm.invoke(forecaster_prompt)
                          individual_forecasts.append(response)
                          print(f"      ✅ Forecast {i+1} completed")
                          await asyncio.sleep(1)  # Rate limiting
                      except Exception as e:
                          print(f"      ❌ Forecast {i+1} failed: {e}")
                          individual_forecasts.append(f"Forecast {i+1} failed: {e}")

                  print(f"✅ Generated {len(individual_forecasts)} individual forecasts")

                  # Step 5: Synthesis Phase
                  print("\\n🔗 STEP 5: SYNTHESIS PHASE")

                  synthesis_prompt = f"""Synthesize these forecasts for the question: {question.question_text}

          Individual Forecasts:
          {chr(10).join([f"Forecast {i+1}: {forecast}" for i, forecast in enumerate(individual_forecasts)])}

          Task:
          1. Analyze consensus and disagreements
          2. Weigh reasoning and evidence
          3. Provide final probability (0-100%)
          4. Give comprehensive reasoning
          5. Format: "Probability: XX% - [Yes/No]"

          Synthesize thoughtfully and provide evidence-based conclusion.
          """

                  try:
                      print("🔄 Running synthesis...")
                      synthesis_response = await synthesizer_llm.invoke(synthesis_prompt)
                      print(f"✅ Synthesis completed ({len(synthesis_response)} chars)")
                  except Exception as e:
                      print(f"❌ Synthesis failed: {e}")
                      synthesis_response = f"Synthesis failed: {e}"

                  # Step 6: Save comprehensive output
                  print("\\n📋 STEP 6: SAVING COMPREHENSIVE OUTPUT")

                  timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                  output_file = f"complete_potus_forecast_{timestamp}.md"

                  content = f"""# Complete POTUS End-to-End Forecast

          **Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
          **Question:** {question.question_text}
          **URL:** {question.page_url}
          **Question Type:** {type(question).__name__}

          ## Model Configuration
          **All models used are FREE OpenRouter models:**
          - Research: {researcher_llm.model_chain[0]} (primary)
          - Forecasting: {forecaster_llm.model_chain[0]} (primary)
          - Synthesis: {synthesizer_llm.model_chain[0]} (primary)

          **Complete fallback chains:**
          Research: {len(researcher_llm.model_chain)} models
          Forecasting: {len(forecaster_llm.model_chain)} models
          Synthesis: {len(synthesizer_llm.model_chain)} models

          ## Process Steps Completed:
          ✅ 1. Found POTUS tournament questions
          ✅ 2. Research Phase - Comprehensive analysis
          ✅ 3. Individual Forecasts - {len(individual_forecasts)} model predictions
          ✅ 4. Synthesis Phase - Combined expert consensus
          ✅ 5. Final Prediction - Evidence-based recommendation

          ## Research Output

          {research_response}

          ## Individual Forecasts

          """

                  for i, forecast in enumerate(individual_forecasts, 1):
                      content += f"### Forecaster {i}\\n\\n{forecast}\\n\\n"

                  content += f"""## Synthesis Output

          {synthesis_response}

          ## System Performance

          ✅ API Authentication: Working with GitHub secrets
          ✅ Free Model Configuration: All models accessible
          ✅ POTUS Tournament Questions: Successfully found and processed
          ✅ Complete Multiforecaster Process: Research → Forecasts → Synthesis
          ✅ End-to-End Execution: Full forecasting pipeline completed

          **🎯 CONCLUSION: Complete POTUS end-to-end forecasting successful!**
          """

                  with open(output_file, 'w', encoding='utf-8') as f:
                      f.write(content)

                  print(f"✅ Comprehensive output saved: {output_file}")

                  # Verify success
                  if "All 9 models in fallback chain failed" in research_response or len(individual_forecasts) == 0:
                      print("❌ MULTIFORECASTER PROCESS FAILED!")
                      return False

                  print("\\n" + "=" * 60)
                  print("🎉 COMPLETE POTUS END-TO-END FORECASTING COMPLETED!")
                  print("✅ Used real POTUS Predictions question")
                  print("✅ Complete multiforecaster process executed")
                  print("✅ All outputs saved")
                  print(f"📄 Report: {output_file}")
                  print("=" * 60)

                  return True

              except Exception as e:
                  print(f"❌ Complete POTUS forecast failed: {str(e)}")
                  import traceback
                  traceback.print_exc()
                  return False

          # Run the complete forecasting
          success = asyncio.run(complete_potus_forecast())
          if success:
              print("\\n🎉 COMPLETE POTUS FORECASTING SUCCESSFUL!")
          else:
              print("\\n❌ COMPLETE POTUS FORECASTING FAILED!")
          EOF

          echo "=== Complete POTUS Forecasting completed at $(date) ==="

      - name: Upload Complete Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: complete-potus-results-${{ github.run_number }}
          path: complete_potus_forecast_*.md
          retention-days: 30

    env:
      GITHUB_ACTIONS: "true"
      METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENAI_DISABLE_TRACE: "true"
      OPENAI_ORGANIZATION: ""