name: Quick Submission Test

on:
  workflow_dispatch:

jobs:
  quick_submission_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          echo "=== Installing dependencies ==="
          pip install forecasting-tools python-dotenv asyncio

      - name: Quick Submission Test
        run: |
          echo "=== Starting Quick Submission Test at $(date) ==="

          python3 test_submission_basic.py

          echo "=== Quick Submission Test completed at $(date) ==="

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: quick-submission-results-${{ github.run_number }}
          path: submission_*.md
          retention-days: 7

    env:
      GITHUB_ACTIONS: "true"
      METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENAI_DISABLE_TRACE: "true"
      OPENAI_ORGANIZATION: ""