name: Simple Tournament Discovery

on:
  push:
    branches: [ main ]

jobs:
  simple_discovery:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          echo "=== Installing dependencies ==="
          pip install forecasting-tools python-dotenv

      - name: Test tournament discovery
        run: |
          echo "=== Simple Tournament Discovery Test ==="
          python test_tournament_only.py
        env:
          GITHUB_ACTIONS: "true"
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
          OPENAI_DISABLE_TRACE: "true"

      - name: Check results
        run: |
          echo "=== Checking Results ==="
          ls -la brightline_found_*.txt 2>/dev/null || echo "No brightline files found"
          if ls brightline_found_*.txt 1> /dev/null 2>&1; then
            echo "✅ Tournament discovery successful!"
            echo "Files created:"
            ls brightline_found_*.txt
            echo "Content preview:"
            head -10 brightline_found_*.txt
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add brightline_found_*.txt
            git commit -m "Tournament discovery successful - found Brightline questions"
            git push
          else
            echo "❌ Tournament discovery failed - no files created"
          fi