name: Test Free Models Configuration

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test_free_models:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Test free models configuration
        run: |
          echo "=== Testing Current Free Model Configuration ==="
          echo "This will verify that the free-only model setup works properly"
          poetry run python test_free_models_config.py
        env:
          GITHUB_ACTIONS: "true"
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_DISABLE_TRACE: "true"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: free-models-test-${{ github.run_number }}
          path: outputs/free_models_test_*.md
          retention-days: 7