name: Test Final API Calls

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test_api_calls:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Test final API calls with fixed authentication
        run: |
          echo "=== Testing final API calls with fixed authentication ==="
          echo "This will verify that the API key fix works properly"
          poetry run python test_final_api_calls.py
        env:
          GITHUB_ACTIONS: "true"
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_DISABLE_TRACE: "true"