name: Test POTUS Tournament

on:
  workflow_dispatch:

jobs:
  test_potus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      - name: Install Dependencies
        run: poetry install
      - name: Test POTUS Tournament Configuration
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          poetry run python main.py --mode tournament
        continue-on-error: true
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: potus-test-results
          path: outputs/