name: Test Current Configuration

on:
  workflow_dispatch:

jobs:
  test_config:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Test current model configuration
        run: |
          echo "=== Testing CURRENT Model Configuration ==="
          echo "This will show exactly what models GitHub Actions is using"
          poetry run python debug_models.py
        env:
          GITHUB_ACTIONS: "true"
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_DISABLE_TRACE: "true"

      - name: Run on Brightline Watch questions
        run: |
          echo "=== Running on Brightline Watch Tournament ==="
          echo "Testing with actual tournament questions"
          poetry run python main.py --mode tournament || echo "Tournament completed with some issues"
        env:
          GITHUB_ACTIONS: "true"
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_DISABLE_TRACE: "true"
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-outputs-${{ github.run_number }}
          path: outputs/
          retention-days: 7