name: Test API Authentication

on:
  workflow_dispatch:

jobs:
  test_api_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          echo "=== Installing test dependencies ==="
          pip install forecasting-tools python-dotenv asyncio

      - name: Test API Authentication
        run: |
          echo "=== Testing API Authentication at $(date) ==="

          python3 test_minimal.py

          echo "=== API Authentication test completed at $(date) ==="

    env:
      GITHUB_ACTIONS: "true"
      METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENAI_DISABLE_TRACE: "true"
      OPENAI_ORGANIZATION: ""